
class: center, middle

# Orientation

## Welcome to Introductory Computer Programming


---


# About this course

- This is a __compulsory non-credit course__

	- Does not count towards composite score
	
	- But you still need to pass (35%)

--

- Goal: Develop programming skills and learn related theory

- These will be useful in several other courses


---

# About this course

- Runs over two semesters

- First semester timing: 2:30-3:30pm Tuesdays and Thursdays

--

- Usual plan:

	- Regular classes during first sememster
	
	- Projects during the second semester
	
- Will depend on how we progress


---

# Grading scheme

- Endterm exam - written: 20% (end of first semester)

- Endterm exam - practical: 20% (end of first / second semester)

- Assignments: 30%

- Projects: 30%


---

# Teaching plan

- Classes will be online on zoom

- Course material will be available through [moodle](https://courses.isid.ac.in)

	- Lecture slides
	
	- Links to video recordings
	
	- Assignments etc.
	
--

- No classes this week (except this orientation)

	- This is to help you get settled into the other courses

	- Ignore the zoom invite you will get for Thursday

--

- However, there is an _assignment_: Fill up a survey on moodle

---

# Zoom guidelines

- Two one-hour classes per week, starting next Tuesday

- General plan: half-hour for lectures, half-hour for discussions

- Zoom session will be recorded and made available through moodle

--

- Use your full name on zoom

- Keep yourself muted, except to ask questions (any time)

- If possible, turn on your video when asking questions


---

class: center, middle

# Any questions?


---

# Tasks before next class

- Fill up the survey on moodle (by Friday)

- If you can, install R and RStudio on your computer

	- For Windows, R can be installed from [here](https://cran.r-project.org/bin/windows/base/)

	- RStudio (Desktop) is available [here](https://rstudio.com/products/rstudio/download/#download) 

- If you have problems, start a new thread in the moodle discussion forum

- We will discuss any problems in the next class

--

- Reminder: no class this Thursday (ignore zoom invite)


